-- MySQL Script generated by MySQL Workbench
-- Thu Aug 16 09:50:50 2018
-- Model: Park Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ParkDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ParkDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ParkDB` DEFAULT CHARACTER SET utf8 ;
USE `ParkDB` ;

-- -----------------------------------------------------
-- Table `ParkDB`.`Forest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkDB`.`Forest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tree_kind` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL DEFAULT 'natural',
  `status` TINYINT NULL DEFAULT 1 COMMENT '1 = healthy, 0 = sick',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkDB`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkDB`.`Accounts` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL COMMENT 'exists only two of them:owner and forester.\n',
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ParkDB`.`Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ParkDB`.`Requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `work_kind` VARCHAR(45) NOT NULL,
  `id_owner` INT NOT NULL,
  `id_forester` INT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tree_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Requests_Forest_idx` (`tree_id` ASC) VISIBLE,
  INDEX `fk_Requests_Accounts1_idx` (`id_owner` ASC) VISIBLE,
  INDEX `fk_Requests_Accounts2_idx` (`id_forester` ASC) VISIBLE,
  CONSTRAINT `fk_Requests_Forest`
    FOREIGN KEY (`tree_id`)
    REFERENCES `ParkDB`.`Forest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requests_Accounts1`
    FOREIGN KEY (`id_owner`)
    REFERENCES `ParkDB`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Requests_Accounts2`
    FOREIGN KEY (`id_forester`)
    REFERENCES `ParkDB`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
